<script setup>
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import QuestionCard from '../components/QuestionCard.vue'; import ProgressBar from '../components/ProgressBar.vue'; import QuizResult from '../components/QuizResult.vue'
import { getDailyQuestions, saveAnswer, calculateScore, saveSession, generateRandomQuestions, getWrongQuestions } from '../utils/quizEngine'
import { getBookmarks, setBookmarks } from '../utils/storage'; import allQuestions from '../data/questions.json'; import { formatDuration } from '../utils/dateUtils'
const route=useRoute(); const category=ref(route.query.category||'Semua'); const difficulty=ref('Semua'); const current=ref(0); const answers=ref({}); const doubtful=ref([]); const questions=ref([]); const startedAt=ref(new Date().toISOString()); const seconds=ref(0); const result=ref(null); const notice=ref('')
function load(){let data=getDailyQuestions({category:category.value}); questions.value=data.questions; answers.value={...(data.answers||{})}; doubtful.value=data.doubtful||[]; startedAt.value=data.startedAt||new Date().toISOString(); notice.value=data.notice||''; result.value=null; current.value=0}
function applyFilter(){let pool=category.value==='Semua'?allQuestions:allQuestions.filter(q=>q.kategori===category.value); if(difficulty.value!=='Semua') pool=pool.filter(q=>q.tingkat_kesulitan===difficulty.value); if(difficulty.value==='Pernah salah') pool=getWrongQuestions(); questions.value=generateRandomQuestions(pool,50); answers.value={}; doubtful.value=[]; startedAt.value=new Date().toISOString(); result.value=null; current.value=0; notice.value=questions.value.length<50?`Soal tersedia ${questions.value.length} dari target 50.`:''}
function answer(key){const q=questions.value[current.value]; answers.value={...answers.value,[q.id]:key}; saveAnswer(q,key,'daily')}
function bookmark(){const id=questions.value[current.value].id; const b=getBookmarks(); setBookmarks(b.includes(id)?b.filter(x=>x!==id):[...b,id])}
function toggleDoubt(){const id=questions.value[current.value].id; doubtful.value=doubtful.value.includes(id)?doubtful.value.filter(x=>x!==id):[...doubtful.value,id]}
function finish(){result.value=saveSession({title:'Latihan Harian',category:category.value,questions:questions.value,answers:answers.value,startedAt:startedAt.value,doubtful:doubtful.value})}
const score=computed(()=>calculateScore(questions.value,answers.value)); const q=computed(()=>questions.value[current.value]); const bookmarks=computed(getBookmarks)
onMounted(()=>{load(); setInterval(()=>seconds.value++,1000)})
</script>
<template><section class="page"><h1>Latihan Harian</h1><p class="lead">Satu soal per halaman, jawaban tersimpan otomatis, timer berjalan selama latihan.</p><div class="toolbar card"><select v-model="category"><option>Semua</option><option>SIMAK UI</option><option>LPDP</option><option>Onkologi Radiasi</option></select><select v-model="difficulty"><option>Semua</option><option>Mudah</option><option>Sedang</option><option>Sulit</option><option>Pernah salah</option></select><button class="btn" @click="category==='Semua'&&difficulty==='Semua'?load():applyFilter()">Mulai / Terapkan</button><span class="pill">Timer {{ formatDuration(seconds) }}</span></div><div v-if="notice" class="alert">{{ notice }}</div><ProgressBar :value="score.answered" :max="questions.length || 50" label="Jawaban tersimpan"/><QuizResult v-if="result" :result="result" @restart="load" @review="result=null"/><QuestionCard v-else :question="q" :number="current+1" :total="questions.length" :selected="answers[q?.id]" :show-answer="!!answers[q?.id]" :bookmarked="bookmarks.includes(q?.id)" :doubtful="doubtful.includes(q?.id)" @answer="answer" @bookmark="bookmark" @doubtful="toggleDoubt" @prev="current=Math.max(0,current-1)" @next="current=Math.min(questions.length-1,current+1)" @finish="finish"/></section></template>
